# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "America/Fortaleza"
    labels:
      - "npm"
      - "dependencies"
    target-branch: "dev"
    groups:
      dev-dependencies:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "prettier*"
        # For Prettier, ignore all updates for minor and patch versions
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/apps/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
